version: '3.5'

networks:
  host_network:
    external: true
    name: host
  private:
    external: true

    
services:
  
  sonda:
    image: iagofcfm/sonda:latest
    networks:
      - private
    volumes:
      - web_shared_folder:/data/images
      - videos:/tmp/videos
      - webgrabplus_data:/opt/data_manager/epg_data
    environment:
      - VIDEOMOS_USER
      - VIDEOMOS_PASSWORD
      - API_PORT
      - DB_PORT
      - VIDEOMOS_LOG_LEVEL=WARNING
      - VIDEOMOS_MAX_RAM_MB=1500
      - VQPREDICTION_MODE=production
      - LANG=es_ES.UTF-8
      - LANGUAGE=es_ES.UTF-8
      - LC_ALL=es_ES.UTF-8
      - TZ=Europe/Madrid
    depends_on:
      - mongo
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
      placement:
        constraints: [node.hostname == $NODE_HOSTNAME]

  websonda:
    image: iagofcfm/sonda:latest-w
    networks:
      - private
    volumes:
      - web_shared_folder:/usr/src/nuxt-app/static/image/frame
    environment:
      - API_PORT=${API_PORT}
      - NUXT_PORT=${NUXT_PORT}
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
      placement:
        constraints: [node.hostname == $NODE_HOSTNAME ]
          
  mongo:
    image: mongo:4.2.9
    networks:
      - private
    entrypoint: mongod --port ${DB_PORT} --wiredTigerCacheSizeGB ${VIDEOMOS_DBCACHE_GB} --syslog
    volumes:
      - mongo:/data/db
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
      placement:
        constraints: [node.hostname == $NODE_HOSTNAME]

  webgrabplus:
    image: linuxserver/webgrabplus:V3.1.0-ls61
    networks:
      - private
    entrypoint: ["/bin/bash", "/config/entrypoint.sh"]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - webgrabplus_config:/config
      - webgrabplus_data:/data
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
      placement:
        constraints: [node.hostname == $NODE_HOSTNAME]
    logging:
      driver: fluentd
      options:
        tag: ${NODE_HOSTNAME}.sonda_${API_PORT}.webgrabplus
        fluentd-async-connect: "true"
     
    
volumes:
  videos: # Write here the path of the VoD folder to use in VideoMOS 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD
  webgrabplus_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/epg_config
  webgrabplus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/epg_data
  mongo:
  web_shared_folder: