version: '2'
services:
  sonda:
    image: iagofcfm/sonda:1.6.0
    network_mode: "host"
    volumes:
      - ./${SHARED_FOLDER}:/data/images
      - videos:/tmp/videos
      - webgrabplus_data:/opt/data_manager/epg_data
    environment:
      - API_PORT
      - DB_PORT
      - VIDEOMOS_LOG_LEVEL=WARNING
      - VIDEOMOS_MAX_RAM_MB=1500
      - VQPREDICTION_MODE=production
      - LANG=es_ES.UTF-8
      - LANGUAGE=es_ES.UTF-8
      - LC_ALL=es_ES.UTF-8
      - TZ=Europe/Madrid
    depends_on:
      - mongo
  websonda:
    image: iagofcfm/sonda:1.6.0-w
    network_mode: "host"
    volumes:
      - ./${SHARED_FOLDER}:/usr/src/nuxt-app/static/image/frame
    environment:
      - API_PORT=${API_PORT}
      - NUXT_PORT=${NUXT_PORT}
  mongo:
    image: mongo:4.2
    network_mode: "host"
    entrypoint: mongod --port ${DB_PORT} --wiredTigerCacheSizeGB ${VIDEOMOS_DBCACHE_GB} --syslog
  webgrabplus:
    image: linuxserver/webgrabplus:V2.1.0-ls54
    network_mode: "host"
    entrypoint: ["/bin/bash", "/config/entrypoint.sh"]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - webgrabplus_config:/config
      - webgrabplus_data:/data
    restart: on-failure
volumes:
  webgrabplus_config:
    external: true
  webgrabplus_data:
    external: true
  # Write here the path of the VoD folder to use in VideoMOS
  videos:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/victor/code/sonda-docker/test-contents/videos
