version: '2'
services:
  sonda:
    image: iagofcfm/sonda:1.0.0
    container_name: ${API_PORT}_sonda
    network_mode: "host"
    volumes:
      - ./${SHARED_FOLDER}:/opt/videoqualityprobe/images
    environment:
      - API_PORT=${API_PORT}
      - DB_PORT=${DB_PORT}
  websonda:
    image: iagofcfm/sonda:1.0.0-w
    container_name: ${API_PORT}_websonda
    network_mode: "host"
    volumes:
      - ./${SHARED_FOLDER}:/usr/src/nuxt-app/static/image/frame
    environment:
      - API_PORT=${API_PORT}
      - WEB_PORT=${WEB_PORT}
